# Generated by Django 5.0.6 on 2024-06-24 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_message_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='content',
            new_name='_input',
        ),
        migrations.RemoveField(
            model_name='message',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='message',
            name='_output',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
    ]
